# Generated by Django 5.1 on 2024-08-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Create_At', models.IntegerField()),
                ('Description', models.CharField(max_length=500)),
                ('Deadline', models.IntegerField()),
            ],
        ),
    ]
