# Generated by Django 5.1 on 2024-08-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Finished_At',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='Create_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
