# Generated by Django 5.1 on 2024-08-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_list_finished_at_alter_list_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='Finished_At',
            field=models.DateTimeField(),
        ),
    ]
