# Generated by Django 5.1 on 2024-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_list_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='Finished_At',
            field=models.DateTimeField(blank=True),
        ),
    ]
