# Generated by Django 5.1 on 2024-09-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_list_finished_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeScale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='Create_At',
            field=models.IntegerField(verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='list',
            name='Deadline',
            field=models.IntegerField(verbose_name='Prazo de'),
        ),
        migrations.AlterField(
            model_name='list',
            name='Description',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='list',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='list',
            name='TimeScale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_TimeScale', to='app.timescale'),
        ),
    ]
