# Generated by Django 5.1 on 2024-09-09 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_timescale_alter_list_create_at_alter_list_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='Create_At',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='list',
            name='Deadline',
            field=models.IntegerField(null=True, verbose_name='Prazo de'),
        ),
        migrations.AlterField(
            model_name='list',
            name='Finished_At',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='TimeScale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_TimeScale', to='app.timescale'),
        ),
    ]
