# Generated by Django 5.1 on 2024-09-10 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_list_create_at_alter_list_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='list',
            name='TimeScale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_TimeScale', to='app.timescale', verbose_name=''),
        ),
    ]
